import type { TextChannel } from 'discord.js';

/**
 * How far back to look when deciding whether Alex has said something before.
 * 200 messages in a quiet server is months of history; in a busy one it is the
 * recent past, which is the part anyone would notice a repeat in.
 */
const HISTORY_LIMIT = 200;

/**
 * Normalise for comparison: the same joke regenerated by the model comes back
 * with different punctuation and capitalisation, and that should still count as
 * already said.
 */
function normalise(text: string): string {
  return text
    .toLowerCase()
    .replace(/https?:\/\/\S+/g, '')
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Word-overlap ratio, 0..1, against the shorter of the two lines. */
function similarity(a: string, b: string): number {
  const wa = new Set(a.split(' ').filter((w) => w.length > 3));
  const wb = new Set(b.split(' ').filter((w) => w.length > 3));
  if (wa.size === 0 || wb.size === 0) return a === b ? 1 : 0;
  let shared = 0;
  for (const w of wa) if (wb.has(w)) shared++;
  return shared / Math.min(wa.size, wb.size);
}

/**
 * Everything Alex has already said in this channel, normalised.
 *
 * Read from the channel rather than from stored state on purpose: the bot runs
 * on an ephemeral worker with no disk that survives a deploy, and the channel
 * is the one record of what was actually posted that cannot drift from reality.
 */
export async function recentBotLines(channel: TextChannel, botId: string): Promise<string[]> {
  try {
    const messages = await channel.messages.fetch({ limit: 100 });
    const lines: string[] = [];
    for (const m of messages.values()) {
      if (m.author.id !== botId) continue;
      const n = normalise(m.content);
      if (n) lines.push(n);
      if (lines.length >= HISTORY_LIMIT) break;
    }
    return lines;
  } catch (err) {
    console.error('[freshness] history fetch failed:', err);
    // An unreadable history means we cannot prove a line is new, and posting a
    // duplicate is the exact complaint this exists to fix -- so treat the
    // channel as if it already contains everything.
    return [];
  }
}

/**
 * True when `candidate` is meaningfully different from everything already said.
 * `null` history (unreadable) is handled by the caller, not here.
 */
export function isFresh(candidate: string, history: string[], threshold = 0.6): boolean {
  const n = normalise(candidate);
  if (!n) return false;
  return !history.some((h) => h === n || similarity(n, h) >= threshold);
}

/**
 * Pick the first candidate that has not been said before. Returns null when
 * every option is a repeat -- in which case saying nothing is correct.
 */
export function firstFresh(candidates: string[], history: string[]): string | null {
  for (const c of candidates) {
    if (isFresh(c, history)) return c;
  }
  return null;
}
